---
title: "List of publications"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

*Maniscalco M*, Brzezinski MA, Thamatrakoln K. Diatom molecular strategies for acclimating to variable light in a dynamic coastal regime. In prep.

*Maniscalco M*, Brzezinski MA, Thamatrakoln K. Diatom molecular strategies for acclimating to variable light in a dynamic coastal regime. In prep.

*Maniscalco, M. A.*, Brzezinski M.A., Krause J.W., Thamatrakoln, K. 2023: “Decoupling silicon metabolism from carbon and nitrogen assimilation poises diatoms to exploit episodic nutrient pulses in a coastal upwelling system,” *Frontiers in Marine Science*, doi:10.3389/FMARS.2023.1291294. 

Ladd TM, Catlett D, **Maniscalco M**, Kim SM, Kelly RL, John SG, Carlson CA, Iglesias-Rodríguez MD. 2023. Wildfire ash deposition fertilizes coastal marine ecosystems. *Proceedings of the Royal Society B*, doi:10.1098/RSPB.2023.1817

**Maniscalco M**, Brzezinski MA, Lampe RH, Cohen NR, McNair HM, Ellis KA, Brown M, Till CP, Twining BS, Bruland KW, Marchetti A, Thamatrakoln K. 2022. Diminished carbon and nitrate assimilation drives changes in Si stoichiometry in an iron-limited diatom assemblage. *ISME Communications*, 2: 57. doi: 10.1038/s43705-022-00136-1

Kranzler CF, Brzezinski MA, Cohen NR, Lampe RH, **Maniscalco M**, Till CP, Mack J, Latham JR, Bruland KW, Twining BS, Marchetti A, Thamatrakoln K. Impaired viral infection and reduced mortality of diatoms in iron-limited oceanic regions. *Nature Geoscience*. 14: 231–237. doi:10.1038/s41561-021-00711-6

Krause JW, Brzezinski MA, Largier JL, McNair HM, **Maniscalco M**, Bidle KD, Allen AE, and Thamatrakoln K. 2020. The interaction of physical and biological factors drives phytoplankton spatial distribution in the northern California Current. *Limnology and Oceanography*. 65: 1974–1989. doi:10.1002/lno.11431

Kranzler CF, Krause JW, Brzezinski MA, Edwards BR, Biggs WP, **Maniscalco M**, McCrow JP, Van Mooy BAS, Bidle KD, Allen AE, Thamatrakoln K. 2021. Silicon limitation facilitates virus infection and mortality of marine diatoms. *Nature Microbiology*. 4: 1790–1797. doi:10.1038/s41564-019-0502-x

**Maniscalco M**, Nannen J, Sodi V, Silver G, Lowrey PL and Bidle KA. 2014. Light-dependent expression of four cryptic archaeal circadian gene homologs. *Frontiers in Microbiology*. 5:79. doi: 10.3389/fmicb.2014.00079




